name = "spring"
main = "index.js"
compatibility_date = "2025-11-09"
workers_dev = true
preview_urls = true
# logpush job is setup to capture from envs ending: log, pro, or one
logpush = false
# use node_compat or custom build
# node_compat = true
send_metrics = false
minify = false

[vars]
UUID = "9bef33ed-40de-492a-8107-4d97090605f9"
PROXYIP = "66.253.7.79"

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = false

# [build]
# command = "npm run deploy"

# [[rules]]
# type = "ESModule"
# globs = ["**/*.js"]
